Revert "Add manifest fragment"
This reverts commit 07176f05f7ee43a9907a1225e094675013ed64ba.

The reason is to avoid the following building error:

FAILED:
build/make/core/base_rules.mk:526:
error: overriding commands for target `out/target/product/x86_64/system/vendor/etc/vintf/manifest/gbm_gralloc_manifest.xml',
previously defined at build/make/core/base_rules.mk:526